apiVersion: v2
name: datahub-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.12013
dependencies:
  - name: kafka
    version: 0.0.1
    repository: file://./subcharts/kafka
    condition: kafka.enabled
  - name: zookeeper
    version: 0.0.1
    repository: file://./subcharts/zookeeper
    condition: zookeeper.enabled
  - name: cp-schema-registry
    version: 0.0.1
    repository: file://./subcharts/cp-schema-registry
    condition: schemaRegistry.enabled
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: postgresql
    version: 11.2.6
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
