apiVersion: v1
kind: Secret
{{- if .Values.existingGmsSecret }}
metadata:
  name: {{ .Values.existingGmsSecret.name | quote }}
type: Opaque
data:
  datahub.gms.secret: {{ .Values.existingGmsSecret.secretValue | b64enc | quote }}
{{- else }}
metadata:
  name: {{ printf "%s-gms-secret" .Release.Name }}
  labels:
    {{- include "datahub-frontend.labels" . | nindent 4 }}
type: Opaque
data:
  datahub.gms.secret: {{ randAlphaNum 10 | b64enc | quote }}
{{- end -}}